server:
  port: 8088
  address: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-restful-notif?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 

    hikari:
      initialization-fail-timeout: 0
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
#    hibernate:
#       Drop n create table, good for testing, comment this in production
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/db-changeLog.xml
    clear-checksums: true
    drop-first: false
  jackson:
    time-zone: Asia/Ho_Chi_Minh
